"""uploads

Revision ID: 2e9a6c5c5c56
Revises: ca1552424fbe
Create Date: 2020-02-23 18:01:31.922088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9a6c5c5c56'
down_revision = 'ca1552424fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('service_number', sa.Integer(), nullable=True),
    sa.Column('operator', sa.String(length=300), nullable=True),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetables')
    op.drop_table('network_maps')
    # ### end Alembic commands ###
