"""bus stops

Revision ID: c63d4e980fc2
Revises: 14ab2859904b
Create Date: 2020-02-18 20:22:25.816197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63d4e980fc2'
down_revision = '14ab2859904b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('x', sa.String(), nullable=False),
    sa.Column('y', sa.String(), nullable=False),
    sa.Column('z', sa.String(), nullable=False),
    sa.Column('photo_front', sa.String(), nullable=False),
    sa.Column('photo_side', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('stop_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_stops')
    # ### end Alembic commands ###
